#%RAML 1.0 DataType
type: array
items:
  properties:
    "street": 
      type: string
      example: "Steinbrueckstrasse"
    "houseNumber": 
      type: number
      example: 114
    "city": 
      type: string 
      example: "Nuremberg"
    "country":
      type: string
      example: "Germany"
    "postalCode": 
      type: number
      example: 90408
        
        
        
