#%RAML 1.0
title: Customer-API
description: When new customer orders a hardware from a reseller’s e-commerce system, the customer data will be also pushed to Fuank’s endpoint via REST API. Fuank is also able to provide customer data to their resellers, if needed. Due to the fact, that current CRM implementation has limited functionality, part of Customer data should be stored in Cosmos DB.
version: v1

traits:
  client-id-required: !include client-id-enforcemnet.raml
types:
  custmor: !include dataTypes/customerType.raml

/customer:
  post:
    is: [client-id-required]
    body:
      application/json:
        type: custmor
        example: !include examples/createCustomerrequest.raml
    responses:
      201:
        body:
          application/json: 
            example: !include examples/createCustomerresponce.raml
      400:
        body:
          application/json:
            example: !include examples/CustomerBadresponce.raml
  put:
    is: [client-id-required]
    body:
      application/json:
        type: custmor
        example: !include examples/updateCustomerrequest.raml
    responses:
      200:
        body:
          application/json:
            example: !include examples/updateCustomerresponce.raml
      400:
        body:
          application/json:
            example: !include examples/CustomerBadresponce.raml
  /{CustomerID}:
    get:
     is: [client-id-required]
     responses:
      200:
        body:
          application/json:
            type: !include dataTypes/customerType.raml
            example: !include examples/createCustomerrequest.raml
      400:
        body:
          application/json:
            example: !include examples/CustomerBadresponce.raml
        
    
                  
          
    
    
  
    
              
        